### ISSUE TITLE
ExceptionHandler

### ISSUE THREAD

**Issue by JNexil** [FRedEnergy/flexy-commands#4]
Annotation "MessageException". If was catched exception with [hasMessage] and [type], to ComnandSender send [toSender] and optionally log to console. Also may be [toSender] localized by i18n.
`@MessageException(Class type, String toSender, boolean log = false,  String hasMessage = "")`

**Comment by JNexil** [comment]
Targets: Class, Method. From class - common.

**Comment by abvadabra** [comment]
Actually, I see no need in this one because the same result can be achieved quite easy by existing api.

**Comment by JNexil** [comment]
But if need many messages, it's might be useful.

**Comment by JNexil** [comment]
And [e.printStacktrace()] for handled exceptions may'be redunant. As example, simple invalid format exception.
